export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: '让理想中的企业级站点开发走进大众 - ServerlessDevs 1024特别奉献',
        author: 'Serverless Devs',
        dateStr: '2021-10-24',
        desc: '本篇文章向大家介绍一下，如何使用serverless devs 结合云产品实现一个具备 高安全，高性能，高体验，高容灾，低成本的web站点',
        link: '/zh-cn/blog/modern-web-application.html',
      },
      {
        title: '从玩具到生产力 1：Serverless Devs的新手引导',
        author: 'Anycodes',
        dateStr: '2021-05-21',
        desc: 'Serverless devs在上个月末，在中国上海，发布了2.0版本，对于很多看热闹的人可能就是一个开源工具的升级更新，但是对于我个人来说，这是Serverless Devs从玩具到生产力的转变。在Serverless Devs 1.0版本，我们是完全的在摸索一条Serverless开发者工具的路，这条路很黑，我们在艰难前进。经过几个月的努力，我们逐渐的看到了光亮，于是在Serverless devs 2.0版本正式发布。',
        link: '/zh-cn/blog/new-serverless-devs-20-1.html',
      },
      {
        title: '阿里云Custom Container的CI/CD最佳实践案例',
        author: 'Anycodes',
        dateStr: '2021-07-2',
        desc: '阿里云Custom Container的CI/CD最佳实践案例介绍',
        link: '/zh-cn/blog/aliyun-custom-container-ci-cd.html',
      },
      {
        title: '阿里云Cloudshell助力Serverless Devs快速体验',
        author: 'Anycodes',
        dateStr: '2021-05-21',
        desc: '如果想要体验命令行工具需要那几步骤？下载客户端->配置密钥信息->下载模板项目->配置相关的资源->部署项目。',
        link: '/zh-cn/blog/aliyun-online-serverless-devs.html',
      },
      {
        title: 'Serverless Devs - SAE与Github Action珠合璧联，让CD从未如此简单',
        author: 'Anycodes',
        dateStr: '2021-07-10',
        desc: 'SAE与Github Action珠联璧合，让CD从未如此简单',
        link: '/zh-cn/blog/aliyun-sae-github-action-cicd.html',
      },
      {
        title: '通过Gitee+Serverless Devs快速实现函数代码更新与版本发布',
        author: 'Anycodes',
        dateStr: '2021-07-2',
        desc: '通过Gitee+Serverless Devs快速实现函数代码更新与版本发布',
        link: '/zh-cn/blog/gitee-gitee-go-serverless-devs-ci-cd.html',
      },
      {
        title: '命令行工具升级：不仅仅是更多的Emoji ',
        author: 'Anycodes',
        dateStr: '2021-05-18',
        desc: '安装完一个工具，第一步做什么？敲一下工具的名称，看看这个工具的“葫芦里卖的什么药”：',
        link: '/zh-cn/blog/new-serverless-devs-output-format.html',
      },
      {
        title: 'Serverless-Devs实践-基于Node的前端CICD',
        author: 'ServerlessDevs',
        dateStr: '2021-06-18',
        desc: 'Serverless-Devs实践-基于Node的前端CICD',
        link: '/zh-cn/blog/node-based-frondend-ci-cd.html',
      },
      {
        title: 'Serverless Devs 开源之夏 2021',
        author: 'ServerlessDevs',
        dateStr: '2021-05-1',
        desc: 'Serverless Devs 开源之夏 2021',
        link: '/zh-cn/blog/open-source-summer-2021.html',
      },
      {
        title: 'Serverless-Devs实践-基于 GhostScript 的 PDF 转 JPG',
        author: 'ServerlessDevs',
        dateStr: '2021-05-1',
        desc: 'Serverless-Devs实践-基于 GhostScript 的 PDF 转 JPG',
        link: '/zh-cn/blog/pdf2jpg-custom-runtime-dependent-installation-practices.html',
      },
      {
        title: '从玩具到生产力 2： 从脚手架到快速部署',
        author: 'ServerlessDevs',
        dateStr: '2021-06-21',
        desc: '从玩具到生产力 2： 从脚手架到快速部署',
        link: '/zh-cn/blog/quick-start-go-serverless-devs.html',
      },
      {
        title: 'Serverless Desktop介绍',
        author: 'hanxie-cypto',
        dateStr: '2021-08-06',
        desc: 'Serverless Desktop介绍',
        link: '/zh-cn/blog/sdesktop-intro.html',
      },
      {
        title: '简单几步完成Serverless架构下的Blog建设',
        author: 'Anycodes',
        dateStr: '2021-05-20',
        desc: '简单几步完成Serverless架构下的Blog建设',
        link: '/zh-cn/blog/serverless-devs-and-serverless-blog.html',
      }, {
        title: '如何通过Github Action使用Serverless Devs做CI/CD',
        author: 'Anycodes',
        dateStr: '2021-07-20',
        desc: '如何通过Github Action使用Serverless Devs做CI/CD',
        link: '/zh-cn/blog/serverless-devs-ci-cd-github-action-usage.html',
      }, {
        title: '透过指令集设计去看Serverless Devs 的扩展能力',
        author: 'hanxie-crypto',
        dateStr: '2021-06-04',
        desc: '透过指令集设计去看Serverless Devs 的扩展能力',
        link: '/zh-cn/blog/serverless-devs-cli-intro.html',
      }, {
        title: '阿里云函数计算组件感知线上“异动”：让发布更安全',
        author: 'Anycodes',
        dateStr: '2021-07-12',
        desc: '阿里云函数计算组件感知线上“异动”：让发布更安全',
        link: '/zh-cn/blog/serverless-devs-fc-perception.html',
      }, {
        title: 'Serverless Devs的官网是通过Serverless Devs部署的',
        author: 'Anycodes',
        dateStr: '2021-05-19',
        desc: 'Serverless Devs的官网是通过Serverless Devs部署的',
        link: '/zh-cn/blog/serverless-devs-static-website-and-cd.html',
      }, {
        title: '只更新代码，然后发布版本：基于Serverless Devs原子化操作阿里云函数计算',
        author: 'Anycodes',
        dateStr: '2021-05-19',
        desc: '只更新代码，然后发布版本：基于Serverless Devs原子化操作阿里云函数计算',
        link: '/zh-cn/blog/serverless-devs-update-fc-code.html',
      }, {
        title: '构建高性能Web站点详细教程',
        author: 'Anycodes',
        dateStr: '2021-08-16',
        desc: '构建高性能Web站点详细教程',
        link: '/zh-cn/blog/serverless-site.html',
      }, {
        title: '云效+Serverless Devs快速实现.NET5函数计算代码更新',
        author: 'GotzeWong',
        dateStr: '2021-07-13',
        desc: '云效+Serverless Devs快速实现.NET5函数计算代码更新',
        link: '/zh-cn/blog/yunxiao-dotnet-serverless-devs-ci-cd.html',
      }
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: '让理想中的企业级站点开发走进大众 - ServerlessDevs 1024特别奉献',
        author: 'Serverless Devs',
        dateStr: '2021-10-24',
        desc: '本篇文章向大家介绍一下，如何使用serverless devs 结合云产品实现一个具备 高安全，高性能，高体验，高容灾，低成本的web站点',
        link: '/zh-cn/blog/modern-web-application.html',
      },
      {
        title: '从玩具到生产力 1：Serverless Devs的新手引导',
        author: 'Anycodes',
        dateStr: '2021-05-21',
        desc: 'Serverless devs在上个月末，在中国上海，发布了2.0版本，对于很多看热闹的人可能就是一个开源工具的升级更新，但是对于我个人来说，这是Serverless Devs从玩具到生产力的转变。在Serverless Devs 1.0版本，我们是完全的在摸索一条Serverless开发者工具的路，这条路很黑，我们在艰难前进。经过几个月的努力，我们逐渐的看到了光亮，于是在Serverless devs 2.0版本正式发布。',
        link: '/zh-cn/blog/new-serverless-devs-20-1.html',
      },
      {
        title: '阿里云Custom Container的CI/CD最佳实践案例',
        author: 'Anycodes',
        dateStr: '2021-07-2',
        desc: '阿里云Custom Container的CI/CD最佳实践案例介绍',
        link: '/zh-cn/blog/aliyun-custom-container-ci-cd.html',
      },
      {
        title: '阿里云Cloudshell助力Serverless Devs快速体验',
        author: 'Anycodes',
        dateStr: '2021-05-21',
        desc: '如果想要体验命令行工具需要那几步骤？下载客户端->配置密钥信息->下载模板项目->配置相关的资源->部署项目。',
        link: '/zh-cn/blog/aliyun-online-serverless-devs.html',
      },
      {
        title: 'Serverless Devs - SAE与Github Action珠合璧联，让CD从未如此简单',
        author: 'Anycodes',
        dateStr: '2021-07-10',
        desc: 'SAE与Github Action珠联璧合，让CD从未如此简单',
        link: '/zh-cn/blog/aliyun-sae-github-action-cicd.html',
      },
      {
        title: '通过Gitee+Serverless Devs快速实现函数代码更新与版本发布',
        author: 'Anycodes',
        dateStr: '2021-07-2',
        desc: '通过Gitee+Serverless Devs快速实现函数代码更新与版本发布',
        link: '/zh-cn/blog/gitee-gitee-go-serverless-devs-ci-cd.html',
      },
      {
        title: '命令行工具升级：不仅仅是更多的Emoji ',
        author: 'Anycodes',
        dateStr: '2021-05-18',
        desc: '安装完一个工具，第一步做什么？敲一下工具的名称，看看这个工具的“葫芦里卖的什么药”：',
        link: '/zh-cn/blog/new-serverless-devs-output-format.html',
      },
      {
        title: 'Serverless-Devs实践-基于Node的前端CICD',
        author: 'ServerlessDevs',
        dateStr: '2021-06-18',
        desc: 'Serverless-Devs实践-基于Node的前端CICD',
        link: '/zh-cn/blog/node-based-frondend-ci-cd.html',
      },
      {
        title: 'Serverless Devs 开源之夏 2021',
        author: 'ServerlessDevs',
        dateStr: '2021-05-1',
        desc: 'Serverless Devs 开源之夏 2021',
        link: '/zh-cn/blog/open-source-summer-2021.html',
      },
      {
        title: 'Serverless-Devs实践-基于 GhostScript 的 PDF 转 JPG',
        author: 'ServerlessDevs',
        dateStr: '2021-05-1',
        desc: 'Serverless-Devs实践-基于 GhostScript 的 PDF 转 JPG',
        link: '/zh-cn/blog/pdf2jpg-custom-runtime-dependent-installation-practices.html',
      },
      {
        title: '从玩具到生产力 2： 从脚手架到快速部署',
        author: 'ServerlessDevs',
        dateStr: '2021-06-21',
        desc: '从玩具到生产力 2： 从脚手架到快速部署',
        link: '/zh-cn/blog/quick-start-go-serverless-devs.html',
      },
      {
        title: 'Serverless Desktop介绍',
        author: 'hanxie-cypto',
        dateStr: '2021-08-06',
        desc: 'Serverless Desktop介绍',
        link: '/zh-cn/blog/sdesktop-intro.html',
      },
      {
        title: '简单几步完成Serverless架构下的Blog建设',
        author: 'Anycodes',
        dateStr: '2021-05-20',
        desc: '简单几步完成Serverless架构下的Blog建设',
        link: '/zh-cn/blog/serverless-devs-and-serverless-blog.html',
      }, {
        title: '如何通过Github Action使用Serverless Devs做CI/CD',
        author: 'Anycodes',
        dateStr: '2021-07-20',
        desc: '如何通过Github Action使用Serverless Devs做CI/CD',
        link: '/zh-cn/blog/serverless-devs-ci-cd-github-action-usage.html',
      }, {
        title: '透过指令集设计去看Serverless Devs 的扩展能力',
        author: 'hanxie-crypto',
        dateStr: '2021-06-04',
        desc: '透过指令集设计去看Serverless Devs 的扩展能力',
        link: '/zh-cn/blog/serverless-devs-cli-intro.html',
      }, {
        title: '阿里云函数计算组件感知线上“异动”：让发布更安全',
        author: 'Anycodes',
        dateStr: '2021-07-12',
        desc: '阿里云函数计算组件感知线上“异动”：让发布更安全',
        link: '/zh-cn/blog/serverless-devs-fc-perception.html',
      }, {
        title: 'Serverless Devs的官网是通过Serverless Devs部署的',
        author: 'Anycodes',
        dateStr: '2021-05-19',
        desc: 'Serverless Devs的官网是通过Serverless Devs部署的',
        link: '/zh-cn/blog/serverless-devs-static-website-and-cd.html',
      }, {
        title: '只更新代码，然后发布版本：基于Serverless Devs原子化操作阿里云函数计算',
        author: 'Anycodes',
        dateStr: '2021-05-19',
        desc: '只更新代码，然后发布版本：基于Serverless Devs原子化操作阿里云函数计算',
        link: '/zh-cn/blog/serverless-devs-update-fc-code.html',
      }, {
        title: '构建高性能Web站点详细教程',
        author: 'Anycodes',
        dateStr: '2021-08-16',
        desc: '构建高性能Web站点详细教程',
        link: '/zh-cn/blog/serverless-site.html',
      }, {
        title: '云效+Serverless Devs快速实现.NET5函数计算代码更新',
        author: 'GotzeWong',
        dateStr: '2021-07-13',
        desc: '云效+Serverless Devs快速实现.NET5函数计算代码更新',
        link: '/zh-cn/blog/yunxiao-dotnet-serverless-devs-ci-cd.html',
      }
    ],
  },
};
