site_name: Serverless Devs Docs
site_description: fc3 documentation with Markdown.
site_author: Aliyun ServerlessDevs Team
nav:
  - 首页: index.md
  - Serverless Devs介绍: 
    - Serverless是什么: introduction/what-is-serverless.md
    - Serverless系统整体架构和原理: introduction/serverless-arch.md
    - Serverless适用场景: introduction/serverless-use-cases.md
    - Serverless Devs的架构和原理介绍: introduction/serverless-devs-arch.md
  - 快速入门: getting-started.md
  - 用户手册: 
    - 安装: user-guide/install.md
    - 配置: user-guide/config.md
    - 内置指令: 
      - 概览: user-guide/builtin/index.md
      - Config 密钥配置: user-guide/builtin/config.md
      - Init 项目初始化: user-guide/builtin/init.md
      - Verify 校验Yaml内容: user-guide/builtin/verify.md
      - Preview 预览渲染结果: user-guide/builtin/preview.md
      - Cli 纯命令行模式: user-guide/builtin/cli.md
      - Component 组件信息: user-guide/builtin/component.md
      - Registry 模版管理: user-guide/builtin/registry.md
      - Clean 工具清理: user-guide/builtin/clean.md
      - Set 工具设置: user-guide/builtin/set.md
      - Env 多环境配置: user-guide/builtin/env.md
      - 自定义命令: user-guide/builtin/custom.md
    - 描述文件格式/规范: user-guide/spec.md
    - 阿里云组件:
      - 概览: user-guide/aliyun/index.md
      - fc3组件:
        - Yaml 规范: user-guide/aliyun/fc3/spec.md
        - 构建&部署:
          - 部署: user-guide/aliyun/fc3/deploy.md
          - 构建: user-guide/aliyun/fc3/build.md
          - 移除: user-guide/aliyun/fc3/remove.md
          - 计划变更: user-guide/aliyun/fc3/plan.md
        - 调用&调试:
          - 本地调试: user-guide/aliyun/fc3/local.md      
          - 函数触发: user-guide/aliyun/fc3/invoke.md
          - 实例登录: user-guide/aliyun/fc3/instance.md
        - 发布&配置:
          - 版本: user-guide/aliyun/fc3/version.md      
          - 别名: user-guide/aliyun/fc3/alias.md
          - 预留: user-guide/aliyun/fc3/provision.md
          - 资源配额: user-guide/aliyun/fc3/concurrency.md
          - 层: user-guide/aliyun/fc3/layer.md
        - 其他:
          - 日志查询: user-guide/aliyun/fc3/logs.md      
          - 查看函数: user-guide/aliyun/fc3/info.md
          - 资源同步: user-guide/aliyun/fc3/sync.md
          - fc2.0 yaml 转 fc3.0 yaml: user-guide/aliyun/fc3/s2tos3.md
      - fc3-domain组件:
        - Yaml 规范: user-guide/aliyun/fc3-domain/spec.md
        - 部署: user-guide/aliyun/fc3-domain/deploy.md
        - 计划变更: user-guide/aliyun/fc3-domain/plan.md
        - 查看: user-guide/aliyun/fc3-domain/info.md
        - 删除: user-guide/aliyun/fc3-domain/remove.md
      - flow 组件:
        - Yaml 规范: user-guide/aliyun/flow/spec.md
        - 部署: user-guide/aliyun/flow/deploy.md
        - 查看: user-guide/aliyun/flow/info.md
        - 删除: user-guide/aliyun/flow/remove.md
        - List: user-guide/aliyun/flow/list.md
      - ros组件:
        - Yaml 规范: user-guide/aliyun/ros/spec.md
        - 部署:  user-guide/aliyun/ros/deploy.md
        - 删除:  user-guide/aliyun/ros/remove.md
        - 查看:  user-guide/aliyun/ros/info.md
      - fc组件(旧版/fc2.0):
        - 注意: user-guide/aliyun/fc/index.md
        - 概览: user-guide/aliyun/fc/readme.md
        - 构建&部署:
          - 部署: user-guide/aliyun/fc/command/deploy.md
          - 构建: user-guide/aliyun/fc/command/build.md
          - 移除: user-guide/aliyun/fc/command/remove.md
          - 计划变更: user-guide/aliyun/fc/command/plan.md
        - 调用&调试:
          - 本地调试: user-guide/aliyun/fc/command/local.md
          - 函数触发: user-guide/aliyun/fc/command/invoke.md
          - 实例登录: user-guide/aliyun/fc/command/instance.md
          - 端云联调: user-guide/aliyun/fc/command/proxied.md
        - 发布&配置:
          - 版本: user-guide/aliyun/fc/command/version.md
          - 别名: user-guide/aliyun/fc/command/alias.md
          - 预留: user-guide/aliyun/fc/command/provision.md
          - 按量资源: user-guide/aliyun/fc/command/ondemand.md
          - 层: user-guide/aliyun/fc/command/layer.md
        - 其他:
          - 日志查询: user-guide/aliyun/fc/command/logs.md
          - 查看函数: user-guide/aliyun/fc/command/info.md
          - 资源同步: user-guide/aliyun/fc/command/sync.md
        - Yaml 规范:
          - Yaml 规范: user-guide/aliyun/fc/yaml/readme.md
          - Service 字段: user-guide/aliyun/fc/yaml/service.md
          - function 字段: user-guide/aliyun/fc/yaml/function.md
          - triggers 字段: user-guide/aliyun/fc/yaml/triggers.md
          - customDomains 字段: user-guide/aliyun/fc/yaml/customDomains.md
    - 其他云厂商组件:
      - aws lambda 组件: user-guide/other-vendor/lambda.md
      - 腾讯云 scf 组件: user-guide/other-vendor/scf.md
      - 华为云 function graph 组件: user-guide/other-vendor/fg.md
      - 百度云 cfc 组件: user-guide/other-vendor/cfc.md
    - CICD 平台集成: user-guide/cicd.md
  - 实战系列:
    - 初识 Serverless Devs:  practices/hello-world.md
    - 调试小试牛刀:  practices/debug.md
    - 如何提高构建/部署效率:  practices/efficiency.md
    - 线上问题诊断: practices/troubleshooting.md
    - CICD:  practices/cicd.md
    - 多区域灾备:  practices/multi-region.md
    - 多环境实践: practices/multi-env.md
  - 常见小贴士: user-guide/tips.md
  - 进阶开发者手册: 
    - 命令行设计规范: dev-guide/cli_design.md
    - 应用开发: dev-guide/application.md
    - 组件开发: dev-guide/component.md
    - 插件开发: dev-guide/plugin.md
    - Parameters 参数: dev-guide/parameters.md   
  - 关于我们: about.md

theme:
  name: material
  logo: https://img.alicdn.com/imgextra/i4/O1CN01ovLZD827VpQmSo4Yx_!!6000000007803-55-tps-86-48.svg
  collapse_by_default: true
  features:
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - codehilite:
      guess_lang: true
      #linenums: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink