site:
  name: Serverless Devs
  site: "https://serverless-devs.com/"
  base: "/"
  trailingSlash: "ignore"
  websiteGithubUrl: "https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/blob/main"
  githubUrl: "https://github.com/alibaba/spring-cloud-alibaba"
  logoUrl: "https://img.alicdn.com/imgextra/i4/O1CN01nAxx821DsAIk5F5uC_!!6000000000271-2-tps-667-370.png"

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"
    baiduAnalytics:
      id:
      verification: code-wzq5sw7io3
    aesAnalytics:
      pid: e7WQkK
    clarityAlalytics:
      id: l4jzj6wbhh

# Default SEO metadata
metadata:
  title:
    default: Serverless Devs 官网 - 一键部署AI/WEB/函数应用到多云的开发运维平台
    template: "%s — AstroWind"
  description: "Serverless Devs 是一个开源开放的 Serverless 开发者平台，致力于为开发者提供强大的工具链体系。通过该平台，开发者不仅可以一键体验多云 Serverless 产品，极速部署 Serverless 项目，还可以在 Serverless 应用全生命周期进行项目的管理，并且非常简单快速的将 Serverless Devs 与其他工具/平台进行结合，进一步提升研发、运维效能。"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Serverless Devs
    type: website

sidebar:
  - label: 首页
    link: overview
  - label: Serverless Devs介绍
    items:
      - label: Serverless是什么
        link: introduction/what-is-serverless
      - label: Serverless系统整体架构和原理
        link: introduction/serverless-arch
      - label: Serverless适用场景
        link: introduction/serverless-use-cases
      - label: Serverless Devs的架构和原理
        link: introduction/serverless-devs-arch
  - label: 快速入门
    link: getting-started
  - label: 用户手册
    items:
      - label: 安装
        link: user-guide/install
      - label: 配置
        link: user-guide/config
      - label: 内置指令
        items:
          - label: 概览
            link: user-guide/builtin
          - label: Config 密钥配置
            link: user-guide/builtin/config
          - label: Init 项目初始化
            link: user-guide/builtin/init
          - label: Verify 校验Yaml内容
            link: user-guide/builtin/verify
          - label: Preview 预览渲染结果
            link: user-guide/builtin/preview
          - label: Cli 纯命令行模式
            link: user-guide/builtin/cli
          - label: Component 组件信息
            link: user-guide/builtin/component
          - label: Registry 模版管理
            link: user-guide/builtin/registry
          - label: Clean 工具清理
            link: user-guide/builtin/clean
          - label: Set 工具设置
            link: user-guide/builtin/set
          - label: Env 多环境配置
            link: user-guide/builtin/env
          - label: 自定义命令
            link: user-guide/builtin/custom
      - label: 描述文件格式/规范
        link: user-guide/spec
      - label: 阿里云组件
        items:
          - label: 概览
            link: user-guide/aliyun
          - label: fc3组件
            items:
              - label: Yaml 规范
                link: user-guide/aliyun/fc3/spec
              - label: 构建&部署
                items:
                  - label: 部署
                    link: user-guide/aliyun/fc3/deploy
                  - label: 构建
                    link: user-guide/aliyun/fc3/build
                  - label: 移除
                    link: user-guide/aliyun/fc3/remove
                  - label: 计划变更
                    link: user-guide/aliyun/fc3/plan
              - label: 调用&调试
                items:
                  - label: 本地调试
                    link: user-guide/aliyun/fc3/local
                  - label: 函数触发
                    link: user-guide/aliyun/fc3/invoke
                  - label: 实例登录
                    link: user-guide/aliyun/fc3/instance
              - label: 发布&配置
                items:
                  - label: 版本
                    link: user-guide/aliyun/fc3/version
                  - label: 别名
                    link: user-guide/aliyun/fc3/alias
                  - label: 预留
                    link: user-guide/aliyun/fc3/provision
                  - label: 资源配额
                    link: user-guide/aliyun/fc3/concurrency
                  - label: 层
                    link: user-guide/aliyun/fc3/layer
              - label: 其他
                items:
                  - label: 日志查询
                    link: user-guide/aliyun/fc3/logs
                  - label: 查看函数
                    link: user-guide/aliyun/fc3/info
                  - label: 资源同步
                    link: user-guide/aliyun/fc3/sync
                  - label: fc2.0 yaml 转 fc3.0 yaml
                    link: user-guide/aliyun/fc3/s2tos3
      - label: 其他云厂商组件
        items:
          - label: AWS Lambda 组件
            link: user-guide/other-vendor/lambda
          - label: 腾讯云 SCF 组件
            link: user-guide/other-vendor/scf
          - label: 华为云 Function Graph 组件
            link: user-guide/other-vendor/fg
          - label: 百度云 CFC 组件
            link: user-guide/other-vendor/cfc
      - label: CICD 平台集成
        link: user-guide/cicd
  - label: 实战系列
    items:
      - label: 初识 Serverless Devs
        link: practices/hello-world
      - label: 调试小试牛刀
        link: practices/debug
      - label: 如何提高构建/部署效率
        link: practices/efficiency
      - label: 线上问题诊断
        link: practices/troubleshooting
      - label: CICD
        link: practices/cicd
      - label: 多区域灾备
        link: practices/multi-region
      - label: 多环境实践
        link: practices/multi-env
  - label: 常见小贴士
    link: user-guide/tips
  - label: 进阶开发者手册
    items:
      - label: 命令行设计规范
        link: dev-guide/cli_design
      - label: 应用开发
        link: dev-guide/application
      - label: 组件开发
        link: dev-guide/component
      - label: 插件开发
        link: dev-guide/plugin
      - label: Parameters 参数
        link: dev-guide/parameters
  - label: 关于我们
    link: about


ui:
  colors:
    # 主按钮颜色，一般为主色中间的颜色
    primary: "#557BF7" # green-08
    # 次按钮的颜色，一般为灰色调最浅颜色
    secondary: "#F6F8F8" #moss-01
    # 强调色。"Header"中的联系我们
    accent: "#2A1683" #green-10
    # 中性色。作为大标题的字体颜色
    neutral: "#0C1D0D" #green-14
    # 基础色，用做首页的背景色1
    base-100: "#F6F8F8" # moss-01
    # 信息颜色。Headline的上方小字, Fotter商标字体颜色
    info: "#666963" #gray-10
    info-200: "rgb(229 231 235)"
    info-300: "rgb(209 213 219)"
    info-400: "rgb(156 163 175)"
    info-500: "rgb(107 114 128)"
    # 成功。 Header的分割符、主要特性中的分割符、companiesfeedback中的isGray的背景颜色
    success: "#7E9B99" #moss-08
    # 警告。header中的toggle-trigger-atc颜色
    warning: "#597371" #moss-10
    # 错误。搜索等组件的bgcolor
    error: "#EBEFEF" #moss-02
    # 静音 companiesfeedback中的isLight的背景颜色
    muted: "#D6EAD8" #green-03
    # 搜索/语言切换组件的文字颜色
    link: "#DDE4E4" #moss-03
    # Head的背景色
    head: "#6146B0"
    # 黑色
    black: "#000000"
    # 白色
    white: "#FFFFFF"
    # 主题色
    theme: "#9cb3ff"
    # 重主题色
    theme-500: "#4d76ff"
