site:
  name: Serverless Devs 官网
  site: "https://serverless-devs.com/"
  base: "/"
  trailingSlash: "always"
  websiteGithubUrl: "https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/blob/main"
  githubUrl: "https://github.com/alibaba/spring-cloud-alibaba"
  logoUrl: "https://img.alicdn.com/imgextra/i4/O1CN01nAxx821DsAIk5F5uC_!!6000000000271-2-tps-667-370.png"

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"
    baiduAnalytics:
      id:
      verification: code-wzq5sw7io3
    aesAnalytics:
      pid: e7WQkK
    clarityAlalytics:
      id: l4jzj6wbhh

# Default SEO metadata
metadata:
  title:
    default: Serverless Devs 官网 - 一键部署AI/WEB/函数应用到多云的开发运维平台
    template: "%s — AstroWind"
  description: "Serverless Devs 是一个开源开放的 Serverless 开发者平台，致力于为开发者提供强大的工具链体系。通过该平台，开发者不仅可以一键体验多云 Serverless 产品，极速部署 Serverless 项目，还可以在 Serverless 应用全生命周期进行项目的管理，并且非常简单快速的将 Serverless Devs 与其他工具/平台进行结合，进一步提升研发、运维效能。"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Serverless Devs
    type: website

ui:
  colors:
    # 主按钮颜色，一般为主色中间的颜色
    primary: "#557BF7" # green-08
    # 次按钮的颜色，一般为灰色调最浅颜色
    secondary: "#F6F8F8" #moss-01
    # 强调色。"Header"中的联系我们
    accent: "#2A1683" #green-10
    # 中性色。作为大标题的字体颜色
    neutral: "#0C1D0D" #green-14
    # 基础色，用做首页的背景色1
    base-100: "#F6F8F8" # moss-01
    # 信息颜色。Headline的上方小字, Fotter商标字体颜色
    info: "#666963" #gray-10
    info-200: "rgb(229 231 235)"
    info-300: "rgb(209 213 219)"
    info-400: "rgb(156 163 175)"
    info-500: "rgb(107 114 128)"
    # 成功。 Header的分割符、主要特性中的分割符、companiesfeedback中的isGray的背景颜色
    success: "#7E9B99" #moss-08
    # 警告。header中的toggle-trigger-atc颜色
    warning: "#597371" #moss-10
    # 错误。搜索等组件的bgcolor
    error: "#EBEFEF" #moss-02
    # 静音 companiesfeedback中的isLight的背景颜色
    muted: "#D6EAD8" #green-03
    # 搜索/语言切换组件的文字颜色
    link: "#DDE4E4" #moss-03
    # Head的背景色
    head: "#6146B0"
    # 黑色
    black: "#000000"
    # 白色
    white: "#FFFFFF"
    # 主题色
    theme: "#9cb3ff"
    # 重主题色
    theme-500: "#4d76ff"
