name: Serverless Devs Project CI/CD

on:
  push:
    branches: [main]

jobs:
  serverless-devs-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install -g @serverless-devs/s
      - run: s config add --AccessKeyID ${{secrets.ACCESSKEYID}}  --AccessKeySecret ${{secrets.ACCESSKEYSECRET}} --AccountID ${{secrets.ACCOUNTID}}
      - run: rm -rf .git
      - run: rm -rf .github
      - run: s deploy -t s.oss.yaml
